# Generated by Django 3.0.3 on 2020-02-27 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqdata',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 11, 32, 37, 714090)),
        ),
        migrations.AlterField(
            model_name='reqdata',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reqtype',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
