# Generated by Django 3.0.3 on 2020-02-27 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20200227_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqdata',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 11, 57, 50, 441151)),
        ),
    ]
