# Generated by Django 3.0.3 on 2020-02-27 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20200227_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqdata',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 27, 12, 4, 42, 998748)),
        ),
    ]
