# Generated by Django 3.0.2 on 2020-02-28 11:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20200228_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reqtype',
            name='slug',
        ),
        migrations.AlterField(
            model_name='reqdata',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 16, 35, 4, 334217)),
        ),
        migrations.AlterField(
            model_name='reqdata',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
