# Generated by Django 3.0.2 on 2020-02-29 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_auto_20200228_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reqdata',
            name='date_modified',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 13, 39, 33, 471113)),
        ),
        migrations.AlterField(
            model_name='reqdata',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
